# Generated by Django 4.1.2 on 2022-11-20 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_message"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"ordering": ["created"]},
        ),
    ]
